name: Check for Duplicates

on:
  workflow_dispatch:

jobs:
  check-duplicates:
    runs-on: ubuntu-latest
    steps:
      - name: Check for duplicates
        uses: actions/github-script@v6
        with:
          script: |
            try {
              const { data: issues } = await github.rest.issues.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
              });

              const { data: pullRequests } = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
              });

              const allItems = [...issues, ...pullRequests];

              const duplicates = [];
              for (let i = 0; i < allItems.length; i++) {
                for (let j = i + 1; j < allItems.length; j++) {
                  if (allItems[i].title.toLowerCase() === allItems[j].title.toLowerCase()) {
                    duplicates.push({
                      item1: allItems[i].html_url,
                      item2: allItems[j].html_url
                    });
                  }
                }
              }

              if (duplicates.length > 0) {
                const duplicateMessages = duplicates.map(dup => `Duplicate found: ${dup.item1} and ${dup.item2}`).join('\n');
                core.setFailed(duplicateMessages);
              } else {
                console.log('No duplicates found.');
              }
            } catch (error) {
              core.setFailed(`Error checking for duplicates: ${error.message}`);
            }
        env:
          GITHUB_TOKEN: ${{ secrets.AC_GH_TOKEN }}
