name: Manual PR Action

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull Request number"
        required: true
        type: integer

jobs:
  run-pr-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the base branch of the PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch the full history to allow diffing
          repository: ${{ github.repository }}

      - name: Fetch PR details
        id: pr-details
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.inputs.pr_number }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine base branch
        id: determine-base
        run: |
          echo "::set-output name=BASE_BRANCH::${{ steps.pr-details.outputs.data.base.ref }}"

      - name: Fetch base branch
        run: |
          git fetch origin ${{ steps.determine-base.outputs.BASE_BRANCH }}

      - name: Check out PR's base branch
        run: |
          git checkout ${{ steps.determine-base.outputs.BASE_BRANCH }}

      - name: Check if PR files end with LF
        run: |
          files=$(git diff --name-only ${{ steps.determine-base.outputs.BASE_BRANCH }} HEAD)
          for file in $files; do
            if [ -f "$file" ]; then
              last_char=$(tail -c 1 "$file" | od -An -t uC | tr -d '[:space:]')
              if [ "$last_char" != "10" ]; then
                echo "::error file=$file::The file '$file' does not end with an LF control character. Please review [Contributing to Installomator](https://github.com/Installomator/Installomator/wiki/Contributing-to-Installomator) and update your pull request. We recommend installing/using an EditorConfig plugin for your editor."
                exit 1
              fi
            fi
          done
