name: Rebase from Upstream

# https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#scheduled-events
on:
  schedule: # run every monday at 5:03 AM UTC
    - cron: "3 5 * * 1"  # https://crontab.guru/#3_5_*_*_1

jobs:
  rebase_from_upstream:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: "[checkout] Checkout Code"
      uses: actions/checkout@v2
    - name: "fetch upstream"
      run: |
        git fetch upstream
    - name: "determine and set the BRANCH_NAME"
      run: |
        echo "BRANCH_NAME="automated-updates/`date "+%Y-%m-%d"` >> $GITHUB_ENV
    - name: "checkout new branch"
      run: |
        echo "Creating a new branch:"${{ env.BRANCH_NAME }}
        git checkout -b ${{ env.BRANCH_NAME }}
    - name: "rebase off of upstream"
      run: |
        git rebase upstream
        # TODO: determine wether or not there are any changes so as to not create unnecessary/emtpy PRs.
    - name: "push this new branch"
      run: |
        git push origin
    - name: "create pull request"
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.BRANCH_NAME }}
        commit-message: "Bringing in latest changes from upstream."
        labels: |
          automated
    - name: "tag admins in PR"
      run: |
        echo "TODO"
